version: '3.4'
services:
  webmvc:
    container_name: shop-system
    build:
      context: .
      dockerfile: src/ShopManagementSystem/ShopManagementSystem.Dashboard/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
    ports:
      - "5005:80"